version: '3.1'
services:
  bookmedik:
    container_name: bookmedik-app
    image: usuario/bookmedik:v1
    restart: always
    env_file:
      - .env
#    environment:
#      DB_HOST: ${DB_HOST}
#      DB_USER: ${DB_USER}
#      DB_PASS: ${DB_PASS}
#      DB_NAME: ${DB_NAME}
    ports:
      - 8081:80
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
